# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    version: "OPENAPI_3_0"
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: "alpha" # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: "alpha" # 태그 정렬 기준
    path: /index.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**